fixed the allowed hosts

diff --git a/.github/workflows/ci-cd-abayashop.yml b/.github/workflows/ci-cd-abayashop.yml
--- a/.github/workflows/ci-cd-abayashop.yml
+++ b/.github/workflows/ci-cd-abayashop.yml
@@ -1,59 +1,58 @@
 name: Abaya shop CI CD pipeline
 on:
   push:
-    ##paths: 
-     ## - 'backend/**' 
+    paths:
+      - "backend/**"
     branches:
       - main
       - develop
 jobs:
-    check:
-      runs-on: ubuntu-latest
-      defaults:
-        run:
-          working-directory: backend
-      env:
-          DATABASEURL: ${{secrets.DATABASEURL}}
-          SECRETKEY: ${{secrets.SECRETKEY}}
-      steps:
-        - name: Checkout code
-          uses: actions/checkout@v3
-        - name: Build docker image
-          working-directory: backend
-          run: docker build -t abayashop .
-        - name: run container
-          run: | 
-            docker run -d -p 8000:8000 --name abayashop-container\
-              -e DATABASEURL="$DATABASEURL" \
-              -e SECRETKEY="$SECRETKEY" \
-              abayashop #the end of the build and run phase.
+  check:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: backend
+    env:
+      DATABASE_URL: ${{secrets.DATABASE_URL}}
+      SECRET_KEY: ${{secrets.SECRET_KEY}}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Build docker image
+        working-directory: backend
+        run: docker build -t abayashop .
+      - name: run container
+        run: |
+          docker run -d -p 8000:8000 --name abayashop-container\
+            -e DATABASE_URL="$DATABASE_URL" \
+            -e SECRET_KEY="$SECRET_KEY" \
+            abayashop #the end of the build and run phase.
 
-        - name: Check container
-          run: docker ps -a
-        - name: wait for app fail if it does not start  #Validation step starts here.
-          run: | 
-            for i in {1..10}; do 
-              if curl -s http://localhost:8000; then
-                echo "app is running"
-                exit 0  
-              fi 
-                echo "waiting for app to start"
-                sleep 2
-              done
-              echo "app failed to start"
-              exit 1 
-        - name: Show container logs
-          if: always()
-          run: docker logs abayashop-container
-##exit 0 stops because of success & exit 1 stops because an error or failure.
+      - name: Check container
+        run: docker ps -a
+      - name: wait for app fail if it does not start #Validation step starts here.
+        run: |
+          for i in {1..10}; do 
+            if curl -s http://localhost:8000; then
+              echo "app is running"
+              exit 0  
+            fi 
+              echo "waiting for app to start"
+              sleep 2
+            done
+            echo "app failed to start"
+            exit 1
+      - name: Show container logs
+        if: always()
+        run: docker logs abayashop-container
+      ##exit 0 stops because of success & exit 1 stops because an error or failure.
 
-        - name: List Files 
-          run: ls -la
-        - name: Run Health Check
-          run: curl -f http://localhost:8000/ ##Validation step ends here
-        - name: cleanup container
-          if : always()
-          run: docker stop abayashop-container && docker rm abayashop-container
-        - name: Echo Message
-          run: echo "Hello, a CI/CD successful  "
-        
+      - name: List Files
+        run: ls -la
+      - name: Run Health Check
+        run: curl -f http://localhost:8000/ ##Validation step ends here
+      - name: cleanup container
+        if: always()
+        run: docker stop abayashop-container && docker rm abayashop-container
+      - name: Echo Message
+        run: echo "Hello, a CI/CD successful  "
